### ISSUE TITLE
Need clarification on projected flow

### ISSUE THREAD

**Issue by Ling27** [PRIS-CV/I-Max#2]
HI @RuoyiDu 

I am impressed by this work and especially the idea of projected flow. While I was reading through the section of projected flow in your paper. I am confused in equation 6 and 7. 
![截屏2024-10-31 下午9 12 40](https://github.com/user-attachments/assets/007a3eb7-dfe0-4c9c-84e5-0cc2bbf803d0)

My understanding is that: the projection function P(.) is to project from high-resolution to low-resolution in both image and flow perspective. So in equation 6, the first term (in red box) represents the direction prediction at high-res space and the second item should represents the low-res guidance which should be formulated as either term in the green box from my understanding. I am a bit confused how the low-res guidance is formulated as the residual shown in the blue box. Can you please explain this? 

Thanks!

**Comment by RuoyiDu** [comment]
> HI @RuoyiDu
> 
> I am impressed by this work and especially the idea of projected flow. While I was reading through the section of projected flow in your paper. I am confused in equation 6 and 7. ![截屏2024-10-31 下午9 12 40](https://private-user-images.githubusercontent.com/39073722/381962807-007a3eb7-dfe0-4c9c-84e5-0cc2bbf803d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzQzNDcsIm5iZiI6MTczMDQzNDA0NywicGF0aCI6Ii8zOTA3MzcyMi8zODE5NjI4MDctMDA3YTNlYjctZGZlMC00YzljLTg0ZTUtMGNjMmJiZjgwM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA0MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzBiNGQ3NWE2ZWMzMzliOWUwZjQzZDUxNGQ5MjU3MDg5NjA0ZmZhYzFkYjljOWJjZTIwMjcxZjA0NDc4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9OgtMz9dE6H0gt1X4L_phP1No34dI24bhpdn6yhHSTw)
> 
> My understanding is that: the projection function P(.) is to project from high-resolution to low-resolution in both image and flow perspective. So in equation 6, the first term (in red box) represents the direction prediction at high-res space and the second item should represents the low-res guidance which should be formulated as either term in the green box from my understanding. I am a bit confused how the low-res guidance is formulated as the residual shown in the blue box. Can you please explain this?
> 
> Thanks!

Hi! I'm not sure I fully understand your question, but I can try to explain the meaning of the two items in the green box. Firstly, it might be easier to understand if you think of projection P() as a filtering operation for low-resolution information (i.e., projecting to the low-resolution space). In this context, the first term represents the ideal flow direction in the low-resolution space, while the second term represents the actual flow direction in the low-resolution space. Together, they form a guidance term. Here, we approximate the ideal flow direction in the low-resolution space using the pre-generated low-resolution result and the current noise latents.

**Comment by Ling27** [comment]
Hi! Thanks for the clarification. I can understand now.

**Comment by Ling27** [comment]
Hi @RuoyiDu 
I have one question regarding the output images of the pipeline. 
![截屏2024-11-03 下午9 45 43](https://github.com/user-attachments/assets/df77d006-7480-4864-9116-4dcddb8cf35c)

There are two images generated from the pipeline. Can you explain the differences between them?

Thanks

**Comment by RuoyiDu** [comment]
> Hi @RuoyiDu I have one question regarding the output images of the pipeline. ![截屏2024-11-03 下午9 45 43](https://private-user-images.githubusercontent.com/39073722/382575828-df77d006-7480-4864-9116-4dcddb8cf35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODY5OTksIm5iZiI6MTczMDY4NjY5OSwicGF0aCI6Ii8zOTA3MzcyMi8zODI1NzU4MjgtZGY3N2QwMDYtNzQ4MC00ODY0LTkxMTYtNGRjZGRiOGNmMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDAyMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNWZiOWQ4YTQ3MTBmOTYyODdhMjcyMWU0MWVlZDcxMDQ4NzYxYmVmNDdhOWRjMDEwNmQ2MTlkYzVlODI3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hUd9YGMFRjbSC3uEz3uR734FKooAzohMuOVLyEvtCtg)
> 
> There are two images generated from the pipeline. Can you explain the differences between them?
> 
> Thanks

Hi, images[0] is the resolution extrapolation result, while images[1] is the low-resolution result which we use as the guidance.

**Comment by Ling27** [comment]
Hi, @RuoyiDu 

Images[1] and Images[0] have the same resolution on my experiment. Is it correct?

**Comment by RuoyiDu** [comment]
> Hi, @RuoyiDu
> 
> Images[1] and Images[0] have the same resolution on my experiment. Is it correct?

Ah yes, Images[1] is interpolated to 4096^2 as the guidance, but it is actually generated at 1024^2.
